# Generated by Django 3.2.4 on 2021-07-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Budget', models.IntegerField()),
                ('Savings_Percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expense', models.FloatField()),
                ('Category', models.CharField(choices=[('Food', 'Food'), ('Shopping', 'Shopping'), ('Transportation', 'Transportation'), ('Bills', 'Bills')], max_length=1000)),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
